config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/name'
  get 'users/email'
  get 'welcome/index'
  root 'static_pages#home'
  get 'static_pages/home'
  get '/help',    to:'static_pages#help'
  get '/about',   to:'static_pages#about'
  get 'contact',  to:'static_pages#contact'
  resources :articles
  resources :notebooks #do
  #   get :section_id, to: "notebooks#new" 
  # end
  resources :sections
  resources :tabs
  resources :pages
  resources :paragraphs
  # get  'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true, length: {minimum: 3, maximum: 50}
	validates :description, presence: true, length: {minimum: 10, maximum: 300}

	belongs_to :articleInterface, polymorphic: true
end

app/models/notebook.rb
class Notebook < ActiveRecord::Base
  has_many :sections
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :paragraphs
  belongs_to :tab, :foreign_key => 'tab_id'
  has_many :articles, as: :articleInterface
end

app/models/paragraph.rb
class Paragraph < ActiveRecord::Base
  belongs_to :page, :foreign_key => 'page_id'
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :tabs
  belongs_to :notebook, :foreign_key => 'notebook_id'
  has_many :articles, as: :articleInterface
end

app/models/tab.rb
class Tab < ActiveRecord::Base
  has_many :pages
  belongs_to :section, :foreign_key => 'section_id'
  has_many :articles, as: :articleInterface
end

app/models/user.rb
class User < ApplicationRecord
	validates(:name, presence: true, length: {maximum: 50})
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :set_page, only: [:edit, :update, :show, :destroy]
	def new
		@page = Page.new
	end
	
	def create 
		@page = Page.new(page_params)
		if @page.save
			flash[:notice] = "Page was successfully created"
			redirect_to pages_path
		else
			render 'new'
		end
	end
	
	def show
		@page = Page.includes(:paragraphs).find(params[:id])
	end
	
	def edit
	end
	
	def update
		if @page.update(page_params)
			flash[:notice] = "Page was updated"
			redirect_to pages_path
		else
			flash[:notice] = "Page was not updated"
			render 'edit'
		end
	end
	
	def index
		@pages = Page.all
	end
	
	def destroy
		@page.destroy
		flash[:notice] = "Page was deleted"
		redirect_to pages_path
	end
	
	private
		def page_params
			params.require(:page).permit(:title, :description)
		end
		
		def set_page
			@page = Page.find(params[:id])
		end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
	before_action :set_section, only: [:edit, :update, :show, :destroy]
	def new
		#@section = Section.new
		@notebook = Notebook.find(params[:notebook_id])
  		@section = @notebook.sections
	end
	
	def create 
		@section = Section.new(section_params)
		if @section.save
			flash[:notice] = "Section was successfully created"
			redirect_to sections_path
		else
			render 'new'
		end
	end
	
	def show
		@section = Section.includes(:tabs).find(params[:id])
	end
	
	def edit
	end
	
	def update
		if @section.update(section_params)
			flash[:notice] = "Section was updated"
			redirect_to sections_path
		else
			flash[:notice] = "Section was not updated"
			render 'edit'
		end
	end
	
	def index
		@sections = Section.all
	end
	
	def destroy
		@section.destroy
		flash[:notice] = "Section was deleted"
		redirect_to sections_path
	end
	
	private
		def section_params
			params.require(:section).permit(:title, :description)
		end
		
		def set_section
			@section = Section.find(params[:id])
		end
end

app/controllers/tabs_controller.rb
class TabsController < ApplicationController
	before_action :set_tab, only: [:edit, :update, :show, :destroy]
	def new
		@tab = Tab.new
	end
	
	def create 
		@tab = Tab.new(tab_params)
		if @tab.save
			flash[:notice] = "Tab was successfully created"
			redirect_to tabs_path
		else
			render 'new'
		end
	end
	
	def show
		@tab = Tab.includes(:pages).find(params[:id])
	end
	
	def edit
	end
	
	def update
		if @tab.update(tab_params)
			flash[:notice] = "Tab was updated"
			redirect_to tabs_path
		else
			flash[:notice] = "Tab was not updated"
			render 'edit'
		end
	end
	
	def index
		@tabs = Tab.all
	end
	
	def destroy
		@tab.destroy
		flash[:notice] = "Tab was deleted"
		redirect_to tabs_path
	end
	
	private
		def tab_params
			params.require(:tab).permit(:title, :description)
		end
		
		def set_tab
			@tab = Tab.find(params[:id])
		end
end

app/controllers/user_conntroller.rb
class UsersController < ApplicationController
	def new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/notebook_helper.rb
module NotebookHelper
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/paragraphs_helper.rb
module ParagraphsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tabs_helper.rb
module TabsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/sections/_form.html.erb
<% if @section.errors.any? %>
	 <h2>The following errors prevented the section from saving:</h2>
	 <ul>
	 	<% @section.errors.full_messages.each do |msg|%>
	 		<li><%= msg %></li>
	 	<% end %>
	 </ul>
<% end %>

<%= form_for @section do |f| %>
 <p>
	  <%= f.label :title %><br>
	  <%= f.text_field :title %>
 </p>
 <p>
	  <%= f.label :description %><br>
	  <%= f.text_area :description %>
 </p>
 <p>
  	<%= f.submit %>
 </p>
<% end %>

<%= link_to 'Back', sections_path %>

app/views/sections/application.html.erb
<% flash.each do |name, msg| %>
	<ul>
		<li><%= msg></li>
	</ul>
<%end%>

app/views/sections/edit.html.erb
<h1>Edit a Section</h1> 
<%= render 'form' %>

app/views/sections/index.html.erb
<h1>Listing all Sections</h1> 
<table>
	<tr>
		<th>Title</th>
		<th>Description</th>
	</tr>
	<tr><% @sections.each do |section| %></tr>
		<tr>
			<td><%= section.title %></td>
			<td><%= section.description %></td>
			<td><%= link_to 'Edit ', edit_section_path(section) %></td>
			<td><%= link_to 'Show ', section_path(section) %></td> w
			<td><%= link_to 'Delete ', section_path(section),
 				method: :delete, data: {confirm: "Are you sure you want to delete?"} %></td>
		</tr>
	<%end%>
</table>

app/views/sections/new.html.erb
<h1>New Section</h1>
 
<%= render 'form' %>

app/views/sections/show.html.erb
<h1>Showing selected section</h1>
<p>
	Title: <%= @section.title %>
</p>
<p>
	Description: <%= @section.description %>
</p>

<% @section.tabs.each do |tab| %>

 	<p>
		Title: <%= tab.title %>
	</p>
	<p>
		Description: <%= tab.description %>
	</p>
	<p>
		<%= link_to 'Tab', tab_path(tab.id) %>
	</p>
	
<% end %>

<%= link_to 'Edit', edit_section_path(@section) %>
<%= link_to 'Back', section_path %>